
export default function DashboardPage() {
  return (
    <div>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6><h6>Dashboard</h6>
      <h6>Dashboard</h6>
      <h6>Dashboard</h6>
    </div>
  )
}
